# Generated by Django 5.0.4 on 2025-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=1500)),
                ('degree', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('previous_work', models.TextField(max_length=1500)),
                ('skills', models.TextField(max_length=1500)),
                ('employed', models.BooleanField(default=False)),
            ],
        ),
    ]
