# Generated by Django 5.0.4 on 2025-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
